/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as ResendOTP from "../ResendOTP.js";
import type * as account from "../account.js";
import type * as accountDeletion from "../accountDeletion.js";
import type * as activation from "../activation.js";
import type * as ai_anthropicCache from "../ai/anthropicCache.js";
import type * as ai_budget from "../ai/budget.js";
import type * as ai_budgetCap from "../ai/budgetCap.js";
import type * as ai_byokErrors from "../ai/byokErrors.js";
import type * as ai_circuitBreaker from "../ai/circuitBreaker.js";
import type * as ai_circuitBreakerCore from "../ai/circuitBreakerCore.js";
import type * as ai_coach from "../ai/coach.js";
import type * as ai_coachModelPolicy from "../ai/coachModelPolicy.js";
import type * as ai_coachTools from "../ai/coachTools.js";
import type * as ai_coachingTools from "../ai/coachingTools.js";
import type * as ai_context from "../ai/context.js";
import type * as ai_contextWindow from "../ai/contextWindow.js";
import type * as ai_contextWindowSearchTelemetry from "../ai/contextWindowSearchTelemetry.js";
import type * as ai_createWorkoutBlocks from "../ai/createWorkoutBlocks.js";
import type * as ai_divergenceNote from "../ai/divergenceNote.js";
import type * as ai_estimationTools from "../ai/estimationTools.js";
import type * as ai_evalHarness from "../ai/evalHarness.js";
import type * as ai_evalScenarios from "../ai/evalScenarios.js";
import type * as ai_exclusionTools from "../ai/exclusionTools.js";
import type * as ai_helpers from "../ai/helpers.js";
import type * as ai_liftingSnapshot from "../ai/liftingSnapshot.js";
import type * as ai_memoryFactExtraction from "../ai/memoryFactExtraction.js";
import type * as ai_memoryFactTelemetry from "../ai/memoryFactTelemetry.js";
import type * as ai_modelMessageToolParts from "../ai/modelMessageToolParts.js";
import type * as ai_modelPricing from "../ai/modelPricing.js";
import type * as ai_modelStepTestUtils from "../ai/modelStepTestUtils.js";
import type * as ai_nutritionSnapshot from "../ai/nutritionSnapshot.js";
import type * as ai_otel from "../ai/otel.js";
import type * as ai_programWeekTool from "../ai/programWeekTool.js";
import type * as ai_promptSections from "../ai/promptSections.js";
import type * as ai_providers from "../ai/providers.js";
import type * as ai_rebuildDayTool from "../ai/rebuildDayTool.js";
import type * as ai_recoverySnapshot from "../ai/recoverySnapshot.js";
import type * as ai_resilience from "../ai/resilience.js";
import type * as ai_resilienceCircuitBreaker from "../ai/resilienceCircuitBreaker.js";
import type * as ai_resilienceReporting from "../ai/resilienceReporting.js";
import type * as ai_runTelemetry from "../ai/runTelemetry.js";
import type * as ai_runTelemetryFinishReason from "../ai/runTelemetryFinishReason.js";
import type * as ai_schemas from "../ai/schemas.js";
import type * as ai_searchProvenance from "../ai/searchProvenance.js";
import type * as ai_searchTelemetry from "../ai/searchTelemetry.js";
import type * as ai_snapshotHelpers from "../ai/snapshotHelpers.js";
import type * as ai_stuckMessageWatchdog from "../ai/stuckMessageWatchdog.js";
import type * as ai_timeDecay from "../ai/timeDecay.js";
import type * as ai_tools from "../ai/tools.js";
import type * as ai_trainingSnapshotCache from "../ai/trainingSnapshotCache.js";
import type * as ai_transientErrors from "../ai/transientErrors.js";
import type * as ai_turnLimits from "../ai/turnLimits.js";
import type * as ai_volumeStrengthTool from "../ai/volumeStrengthTool.js";
import type * as ai_weekModificationTools from "../ai/weekModificationTools.js";
import type * as ai_weekReasoning from "../ai/weekReasoning.js";
import type * as ai_weekTools from "../ai/weekTools.js";
import type * as aiUsage from "../aiUsage.js";
import type * as auth from "../auth.js";
import type * as byok from "../byok.js";
import type * as byokProvider from "../byokProvider.js";
import type * as byokShared from "../byokShared.js";
import type * as byokValidation from "../byokValidation.js";
import type * as chat from "../chat.js";
import type * as chatApproval from "../chatApproval.js";
import type * as chatHelpers from "../chatHelpers.js";
import type * as chatProcessing from "../chatProcessing.js";
import type * as checkIns from "../checkIns.js";
import type * as checkIns_content from "../checkIns/content.js";
import type * as checkIns_triggers from "../checkIns/triggers.js";
import type * as coach_exerciseSelection from "../coach/exerciseSelection.js";
import type * as coach_goalConfig from "../coach/goalConfig.js";
import type * as coach_missedSessionDetection from "../coach/missedSessionDetection.js";
import type * as coach_normalizeBlocks from "../coach/normalizeBlocks.js";
import type * as coach_periodization from "../coach/periodization.js";
import type * as coach_personalMrv from "../coach/personalMrv.js";
import type * as coach_personalMrvHistory from "../coach/personalMrvHistory.js";
import type * as coach_prDetection from "../coach/prDetection.js";
import type * as coach_pushAndVerify from "../coach/pushAndVerify.js";
import type * as coach_pushAndVerifyContract from "../coach/pushAndVerifyContract.js";
import type * as coach_rebuildDay from "../coach/rebuildDay.js";
import type * as coach_volumeLandmarks from "../coach/volumeLandmarks.js";
import type * as coach_volumeStrengthCorrelation from "../coach/volumeStrengthCorrelation.js";
import type * as coach_weekDayModifications from "../coach/weekDayModifications.js";
import type * as coach_weekModifications from "../coach/weekModifications.js";
import type * as coach_weekProgramming from "../coach/weekProgramming.js";
import type * as coach_weekProgrammingDirect from "../coach/weekProgrammingDirect.js";
import type * as coach_weekProgrammingHelpers from "../coach/weekProgrammingHelpers.js";
import type * as coach_weekPushDraft from "../coach/weekPushDraft.js";
import type * as coach_workoutBlocks from "../coach/workoutBlocks.js";
import type * as coachState from "../coachState.js";
import type * as contact from "../contact.js";
import type * as crons from "../crons.js";
import type * as dashboard from "../dashboard.js";
import type * as dataExport from "../dataExport.js";
import type * as dataExportTypes from "../dataExportTypes.js";
import type * as dataRetention from "../dataRetention.js";
import type * as devTools from "../devTools.js";
import type * as devToolsActions from "../devToolsActions.js";
import type * as discord from "../discord.js";
import type * as email from "../email.js";
import type * as emailChange from "../emailChange.js";
import type * as emailTemplates from "../emailTemplates.js";
import type * as exerciseExclusions from "../exerciseExclusions.js";
import type * as fileGc from "../fileGc.js";
import type * as fitbit_activityPersistence from "../fitbit/activityPersistence.js";
import type * as fitbit_client from "../fitbit/client.js";
import type * as fitbit_config from "../fitbit/config.js";
import type * as fitbit_connections from "../fitbit/connections.js";
import type * as fitbit_normalizers from "../fitbit/normalizers.js";
import type * as fitbit_oauthArtifacts from "../fitbit/oauthArtifacts.js";
import type * as fitbit_oauthFlow from "../fitbit/oauthFlow.js";
import type * as fitbit_sync from "../fitbit/sync.js";
import type * as fitbit_tokenRevocation from "../fitbit/tokenRevocation.js";
import type * as fitbit_wellnessDaily from "../fitbit/wellnessDaily.js";
import type * as garmin_activityNormalizer from "../garmin/activityNormalizer.js";
import type * as garmin_backfill from "../garmin/backfill.js";
import type * as garmin_connections from "../garmin/connections.js";
import type * as garmin_credentials from "../garmin/credentials.js";
import type * as garmin_oauth1 from "../garmin/oauth1.js";
import type * as garmin_oauthFlow from "../garmin/oauthFlow.js";
import type * as garmin_registration from "../garmin/registration.js";
import type * as garmin_trainingApi from "../garmin/trainingApi.js";
import type * as garmin_webhookDispatch from "../garmin/webhookDispatch.js";
import type * as garmin_webhookEvents from "../garmin/webhookEvents.js";
import type * as garmin_webhookPayloads from "../garmin/webhookPayloads.js";
import type * as garmin_webhookSignature from "../garmin/webhookSignature.js";
import type * as garmin_wellnessDaily from "../garmin/wellnessDaily.js";
import type * as garmin_wellnessNormalizers from "../garmin/wellnessNormalizers.js";
import type * as garmin_workoutDelivery from "../garmin/workoutDelivery.js";
import type * as garmin_workoutPayload from "../garmin/workoutPayload.js";
import type * as goals from "../goals.js";
import type * as healthCheck from "../healthCheck.js";
import type * as http from "../http.js";
import type * as httpOrigin from "../httpOrigin.js";
import type * as injuries from "../injuries.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_env from "../lib/env.js";
import type * as lib_posthog from "../lib/posthog.js";
import type * as lib_targetArea from "../lib/targetArea.js";
import type * as libraryWorkouts from "../libraryWorkouts.js";
import type * as liftingCoachProjection from "../liftingCoachProjection.js";
import type * as liftingExport from "../liftingExport.js";
import type * as liftingSessionContract from "../liftingSessionContract.js";
import type * as liftingSessions from "../liftingSessions.js";
import type * as migrations from "../migrations.js";
import type * as migrations_repairOrphanedAuthAccounts from "../migrations/repairOrphanedAuthAccounts.js";
import type * as nutrition from "../nutrition.js";
import type * as nutritionCoachProjection from "../nutritionCoachProjection.js";
import type * as nutritionContract from "../nutritionContract.js";
import type * as nutritionExport from "../nutritionExport.js";
import type * as personalRecords from "../personalRecords.js";
import type * as progressiveOverload from "../progressiveOverload.js";
import type * as prs from "../prs.js";
import type * as rateLimits from "../rateLimits.js";
import type * as recoveryCheckIns from "../recoveryCheckIns.js";
import type * as recoveryExport from "../recoveryExport.js";
import type * as recoveryPreferences from "../recoveryPreferences.js";
import type * as schedule from "../schedule.js";
import type * as stats from "../stats.js";
import type * as strava_activityPersistence from "../strava/activityPersistence.js";
import type * as strava_activitySchema from "../strava/activitySchema.js";
import type * as strava_apiRequest from "../strava/apiRequest.js";
import type * as strava_client from "../strava/client.js";
import type * as strava_config from "../strava/config.js";
import type * as strava_connections from "../strava/connections.js";
import type * as strava_disconnect from "../strava/disconnect.js";
import type * as strava_oauthArtifacts from "../strava/oauthArtifacts.js";
import type * as strava_oauthFlow from "../strava/oauthFlow.js";
import type * as strava_rateLimitBudget from "../strava/rateLimitBudget.js";
import type * as strava_status from "../strava/status.js";
import type * as strava_sync from "../strava/sync.js";
import type * as strava_syncState from "../strava/syncState.js";
import type * as strava_tokenExchange from "../strava/tokenExchange.js";
import type * as strava_tokenRevocation from "../strava/tokenRevocation.js";
import type * as strava_webhook from "../strava/webhook.js";
import type * as strava_webhookProcessor from "../strava/webhookProcessor.js";
import type * as strava_webhookRecovery from "../strava/webhookRecovery.js";
import type * as strava_webhookSignature from "../strava/webhookSignature.js";
import type * as strava_webhookTiming from "../strava/webhookTiming.js";
import type * as threads from "../threads.js";
import type * as tonal_accessories from "../tonal/accessories.js";
import type * as tonal_auth from "../tonal/auth.js";
import type * as tonal_cache from "../tonal/cache.js";
import type * as tonal_cacheRefresh from "../tonal/cacheRefresh.js";
import type * as tonal_cacheRefreshTiering from "../tonal/cacheRefreshTiering.js";
import type * as tonal_client from "../tonal/client.js";
import type * as tonal_connect from "../tonal/connect.js";
import type * as tonal_connectPublic from "../tonal/connectPublic.js";
import type * as tonal_customWorkoutsProjection from "../tonal/customWorkoutsProjection.js";
import type * as tonal_encryption from "../tonal/encryption.js";
import type * as tonal_enrichmentSync from "../tonal/enrichmentSync.js";
import type * as tonal_externalActivitiesProjection from "../tonal/externalActivitiesProjection.js";
import type * as tonal_externalActivitySources from "../tonal/externalActivitySources.js";
import type * as tonal_formattedSummaryProjection from "../tonal/formattedSummaryProjection.js";
import type * as tonal_hardware from "../tonal/hardware.js";
import type * as tonal_historySync from "../tonal/historySync.js";
import type * as tonal_historySyncCore from "../tonal/historySyncCore.js";
import type * as tonal_historySyncMutations from "../tonal/historySyncMutations.js";
import type * as tonal_historySyncPreflight from "../tonal/historySyncPreflight.js";
import type * as tonal_movementMapping from "../tonal/movementMapping.js";
import type * as tonal_movementResolve from "../tonal/movementResolve.js";
import type * as tonal_movementSearch from "../tonal/movementSearch.js";
import type * as tonal_movementSearchQueries from "../tonal/movementSearchQueries.js";
import type * as tonal_movementSync from "../tonal/movementSync.js";
import type * as tonal_mutations from "../tonal/mutations.js";
import type * as tonal_profileBackfill from "../tonal/profileBackfill.js";
import type * as tonal_profileData from "../tonal/profileData.js";
import type * as tonal_proxy from "../tonal/proxy.js";
import type * as tonal_proxyCacheLimits from "../tonal/proxyCacheLimits.js";
import type * as tonal_proxyMemo from "../tonal/proxyMemo.js";
import type * as tonal_proxyProjected from "../tonal/proxyProjected.js";
import type * as tonal_refresh from "../tonal/refresh.js";
import type * as tonal_refreshPublic from "../tonal/refreshPublic.js";
import type * as tonal_resync from "../tonal/resync.js";
import type * as tonal_scheduling from "../tonal/scheduling.js";
import type * as tonal_schedulingReceipts from "../tonal/schedulingReceipts.js";
import type * as tonal_strengthHistoryProjection from "../tonal/strengthHistoryProjection.js";
import type * as tonal_syncQueries from "../tonal/syncQueries.js";
import type * as tonal_tokenQueries from "../tonal/tokenQueries.js";
import type * as tonal_tokenRefresh from "../tonal/tokenRefresh.js";
import type * as tonal_tokenRetry from "../tonal/tokenRetry.js";
import type * as tonal_transforms from "../tonal/transforms.js";
import type * as tonal_types from "../tonal/types.js";
import type * as tonal_validation from "../tonal/validation.js";
import type * as tonal_workoutCatalogSync from "../tonal/workoutCatalogSync.js";
import type * as tonal_workoutDetailProjection from "../tonal/workoutDetailProjection.js";
import type * as tonal_workoutHistoryProxy from "../tonal/workoutHistoryProxy.js";
import type * as tonal_workoutMeta from "../tonal/workoutMeta.js";
import type * as trainingState_read from "../trainingState/read.js";
import type * as trainingState_recovery from "../trainingState/recovery.js";
import type * as trainingState_types from "../trainingState/types.js";
import type * as userActivity from "../userActivity.js";
import type * as userData from "../userData.js";
import type * as userMemoryFacts from "../userMemoryFacts.js";
import type * as userProfileActivity from "../userProfileActivity.js";
import type * as userProfiles from "../userProfiles.js";
import type * as users from "../users.js";
import type * as validators from "../validators.js";
import type * as weekPlanActions from "../weekPlanActions.js";
import type * as weekPlanApproval from "../weekPlanApproval.js";
import type * as weekPlanCompletion from "../weekPlanCompletion.js";
import type * as weekPlanDeletion from "../weekPlanDeletion.js";
import type * as weekPlanDeletionShared from "../weekPlanDeletionShared.js";
import type * as weekPlanDeletionSnapshot from "../weekPlanDeletionSnapshot.js";
import type * as weekPlanDeletionState from "../weekPlanDeletionState.js";
import type * as weekPlanEnriched from "../weekPlanEnriched.js";
import type * as weekPlanHelpers from "../weekPlanHelpers.js";
import type * as weekPlanInternals from "../weekPlanInternals.js";
import type * as weekPlans from "../weekPlans.js";
import type * as workflows from "../workflows.js";
import type * as workoutDeletionGuard from "../workoutDeletionGuard.js";
import type * as workoutDetail from "../workoutDetail.js";
import type * as workoutFeedback from "../workoutFeedback.js";
import type * as workoutPerformanceProjectionFreshness from "../workoutPerformanceProjectionFreshness.js";
import type * as workoutPlans from "../workoutPlans.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  ResendOTP: typeof ResendOTP;
  account: typeof account;
  accountDeletion: typeof accountDeletion;
  activation: typeof activation;
  "ai/anthropicCache": typeof ai_anthropicCache;
  "ai/budget": typeof ai_budget;
  "ai/budgetCap": typeof ai_budgetCap;
  "ai/byokErrors": typeof ai_byokErrors;
  "ai/circuitBreaker": typeof ai_circuitBreaker;
  "ai/circuitBreakerCore": typeof ai_circuitBreakerCore;
  "ai/coach": typeof ai_coach;
  "ai/coachModelPolicy": typeof ai_coachModelPolicy;
  "ai/coachTools": typeof ai_coachTools;
  "ai/coachingTools": typeof ai_coachingTools;
  "ai/context": typeof ai_context;
  "ai/contextWindow": typeof ai_contextWindow;
  "ai/contextWindowSearchTelemetry": typeof ai_contextWindowSearchTelemetry;
  "ai/createWorkoutBlocks": typeof ai_createWorkoutBlocks;
  "ai/divergenceNote": typeof ai_divergenceNote;
  "ai/estimationTools": typeof ai_estimationTools;
  "ai/evalHarness": typeof ai_evalHarness;
  "ai/evalScenarios": typeof ai_evalScenarios;
  "ai/exclusionTools": typeof ai_exclusionTools;
  "ai/helpers": typeof ai_helpers;
  "ai/liftingSnapshot": typeof ai_liftingSnapshot;
  "ai/memoryFactExtraction": typeof ai_memoryFactExtraction;
  "ai/memoryFactTelemetry": typeof ai_memoryFactTelemetry;
  "ai/modelMessageToolParts": typeof ai_modelMessageToolParts;
  "ai/modelPricing": typeof ai_modelPricing;
  "ai/modelStepTestUtils": typeof ai_modelStepTestUtils;
  "ai/nutritionSnapshot": typeof ai_nutritionSnapshot;
  "ai/otel": typeof ai_otel;
  "ai/programWeekTool": typeof ai_programWeekTool;
  "ai/promptSections": typeof ai_promptSections;
  "ai/providers": typeof ai_providers;
  "ai/rebuildDayTool": typeof ai_rebuildDayTool;
  "ai/recoverySnapshot": typeof ai_recoverySnapshot;
  "ai/resilience": typeof ai_resilience;
  "ai/resilienceCircuitBreaker": typeof ai_resilienceCircuitBreaker;
  "ai/resilienceReporting": typeof ai_resilienceReporting;
  "ai/runTelemetry": typeof ai_runTelemetry;
  "ai/runTelemetryFinishReason": typeof ai_runTelemetryFinishReason;
  "ai/schemas": typeof ai_schemas;
  "ai/searchProvenance": typeof ai_searchProvenance;
  "ai/searchTelemetry": typeof ai_searchTelemetry;
  "ai/snapshotHelpers": typeof ai_snapshotHelpers;
  "ai/stuckMessageWatchdog": typeof ai_stuckMessageWatchdog;
  "ai/timeDecay": typeof ai_timeDecay;
  "ai/tools": typeof ai_tools;
  "ai/trainingSnapshotCache": typeof ai_trainingSnapshotCache;
  "ai/transientErrors": typeof ai_transientErrors;
  "ai/turnLimits": typeof ai_turnLimits;
  "ai/volumeStrengthTool": typeof ai_volumeStrengthTool;
  "ai/weekModificationTools": typeof ai_weekModificationTools;
  "ai/weekReasoning": typeof ai_weekReasoning;
  "ai/weekTools": typeof ai_weekTools;
  aiUsage: typeof aiUsage;
  auth: typeof auth;
  byok: typeof byok;
  byokProvider: typeof byokProvider;
  byokShared: typeof byokShared;
  byokValidation: typeof byokValidation;
  chat: typeof chat;
  chatApproval: typeof chatApproval;
  chatHelpers: typeof chatHelpers;
  chatProcessing: typeof chatProcessing;
  checkIns: typeof checkIns;
  "checkIns/content": typeof checkIns_content;
  "checkIns/triggers": typeof checkIns_triggers;
  "coach/exerciseSelection": typeof coach_exerciseSelection;
  "coach/goalConfig": typeof coach_goalConfig;
  "coach/missedSessionDetection": typeof coach_missedSessionDetection;
  "coach/normalizeBlocks": typeof coach_normalizeBlocks;
  "coach/periodization": typeof coach_periodization;
  "coach/personalMrv": typeof coach_personalMrv;
  "coach/personalMrvHistory": typeof coach_personalMrvHistory;
  "coach/prDetection": typeof coach_prDetection;
  "coach/pushAndVerify": typeof coach_pushAndVerify;
  "coach/pushAndVerifyContract": typeof coach_pushAndVerifyContract;
  "coach/rebuildDay": typeof coach_rebuildDay;
  "coach/volumeLandmarks": typeof coach_volumeLandmarks;
  "coach/volumeStrengthCorrelation": typeof coach_volumeStrengthCorrelation;
  "coach/weekDayModifications": typeof coach_weekDayModifications;
  "coach/weekModifications": typeof coach_weekModifications;
  "coach/weekProgramming": typeof coach_weekProgramming;
  "coach/weekProgrammingDirect": typeof coach_weekProgrammingDirect;
  "coach/weekProgrammingHelpers": typeof coach_weekProgrammingHelpers;
  "coach/weekPushDraft": typeof coach_weekPushDraft;
  "coach/workoutBlocks": typeof coach_workoutBlocks;
  coachState: typeof coachState;
  contact: typeof contact;
  crons: typeof crons;
  dashboard: typeof dashboard;
  dataExport: typeof dataExport;
  dataExportTypes: typeof dataExportTypes;
  dataRetention: typeof dataRetention;
  devTools: typeof devTools;
  devToolsActions: typeof devToolsActions;
  discord: typeof discord;
  email: typeof email;
  emailChange: typeof emailChange;
  emailTemplates: typeof emailTemplates;
  exerciseExclusions: typeof exerciseExclusions;
  fileGc: typeof fileGc;
  "fitbit/activityPersistence": typeof fitbit_activityPersistence;
  "fitbit/client": typeof fitbit_client;
  "fitbit/config": typeof fitbit_config;
  "fitbit/connections": typeof fitbit_connections;
  "fitbit/normalizers": typeof fitbit_normalizers;
  "fitbit/oauthArtifacts": typeof fitbit_oauthArtifacts;
  "fitbit/oauthFlow": typeof fitbit_oauthFlow;
  "fitbit/sync": typeof fitbit_sync;
  "fitbit/tokenRevocation": typeof fitbit_tokenRevocation;
  "fitbit/wellnessDaily": typeof fitbit_wellnessDaily;
  "garmin/activityNormalizer": typeof garmin_activityNormalizer;
  "garmin/backfill": typeof garmin_backfill;
  "garmin/connections": typeof garmin_connections;
  "garmin/credentials": typeof garmin_credentials;
  "garmin/oauth1": typeof garmin_oauth1;
  "garmin/oauthFlow": typeof garmin_oauthFlow;
  "garmin/registration": typeof garmin_registration;
  "garmin/trainingApi": typeof garmin_trainingApi;
  "garmin/webhookDispatch": typeof garmin_webhookDispatch;
  "garmin/webhookEvents": typeof garmin_webhookEvents;
  "garmin/webhookPayloads": typeof garmin_webhookPayloads;
  "garmin/webhookSignature": typeof garmin_webhookSignature;
  "garmin/wellnessDaily": typeof garmin_wellnessDaily;
  "garmin/wellnessNormalizers": typeof garmin_wellnessNormalizers;
  "garmin/workoutDelivery": typeof garmin_workoutDelivery;
  "garmin/workoutPayload": typeof garmin_workoutPayload;
  goals: typeof goals;
  healthCheck: typeof healthCheck;
  http: typeof http;
  httpOrigin: typeof httpOrigin;
  injuries: typeof injuries;
  "lib/auth": typeof lib_auth;
  "lib/env": typeof lib_env;
  "lib/posthog": typeof lib_posthog;
  "lib/targetArea": typeof lib_targetArea;
  libraryWorkouts: typeof libraryWorkouts;
  liftingCoachProjection: typeof liftingCoachProjection;
  liftingExport: typeof liftingExport;
  liftingSessionContract: typeof liftingSessionContract;
  liftingSessions: typeof liftingSessions;
  migrations: typeof migrations;
  "migrations/repairOrphanedAuthAccounts": typeof migrations_repairOrphanedAuthAccounts;
  nutrition: typeof nutrition;
  nutritionCoachProjection: typeof nutritionCoachProjection;
  nutritionContract: typeof nutritionContract;
  nutritionExport: typeof nutritionExport;
  personalRecords: typeof personalRecords;
  progressiveOverload: typeof progressiveOverload;
  prs: typeof prs;
  rateLimits: typeof rateLimits;
  recoveryCheckIns: typeof recoveryCheckIns;
  recoveryExport: typeof recoveryExport;
  recoveryPreferences: typeof recoveryPreferences;
  schedule: typeof schedule;
  stats: typeof stats;
  "strava/activityPersistence": typeof strava_activityPersistence;
  "strava/activitySchema": typeof strava_activitySchema;
  "strava/apiRequest": typeof strava_apiRequest;
  "strava/client": typeof strava_client;
  "strava/config": typeof strava_config;
  "strava/connections": typeof strava_connections;
  "strava/disconnect": typeof strava_disconnect;
  "strava/oauthArtifacts": typeof strava_oauthArtifacts;
  "strava/oauthFlow": typeof strava_oauthFlow;
  "strava/rateLimitBudget": typeof strava_rateLimitBudget;
  "strava/status": typeof strava_status;
  "strava/sync": typeof strava_sync;
  "strava/syncState": typeof strava_syncState;
  "strava/tokenExchange": typeof strava_tokenExchange;
  "strava/tokenRevocation": typeof strava_tokenRevocation;
  "strava/webhook": typeof strava_webhook;
  "strava/webhookProcessor": typeof strava_webhookProcessor;
  "strava/webhookRecovery": typeof strava_webhookRecovery;
  "strava/webhookSignature": typeof strava_webhookSignature;
  "strava/webhookTiming": typeof strava_webhookTiming;
  threads: typeof threads;
  "tonal/accessories": typeof tonal_accessories;
  "tonal/auth": typeof tonal_auth;
  "tonal/cache": typeof tonal_cache;
  "tonal/cacheRefresh": typeof tonal_cacheRefresh;
  "tonal/cacheRefreshTiering": typeof tonal_cacheRefreshTiering;
  "tonal/client": typeof tonal_client;
  "tonal/connect": typeof tonal_connect;
  "tonal/connectPublic": typeof tonal_connectPublic;
  "tonal/customWorkoutsProjection": typeof tonal_customWorkoutsProjection;
  "tonal/encryption": typeof tonal_encryption;
  "tonal/enrichmentSync": typeof tonal_enrichmentSync;
  "tonal/externalActivitiesProjection": typeof tonal_externalActivitiesProjection;
  "tonal/externalActivitySources": typeof tonal_externalActivitySources;
  "tonal/formattedSummaryProjection": typeof tonal_formattedSummaryProjection;
  "tonal/hardware": typeof tonal_hardware;
  "tonal/historySync": typeof tonal_historySync;
  "tonal/historySyncCore": typeof tonal_historySyncCore;
  "tonal/historySyncMutations": typeof tonal_historySyncMutations;
  "tonal/historySyncPreflight": typeof tonal_historySyncPreflight;
  "tonal/movementMapping": typeof tonal_movementMapping;
  "tonal/movementResolve": typeof tonal_movementResolve;
  "tonal/movementSearch": typeof tonal_movementSearch;
  "tonal/movementSearchQueries": typeof tonal_movementSearchQueries;
  "tonal/movementSync": typeof tonal_movementSync;
  "tonal/mutations": typeof tonal_mutations;
  "tonal/profileBackfill": typeof tonal_profileBackfill;
  "tonal/profileData": typeof tonal_profileData;
  "tonal/proxy": typeof tonal_proxy;
  "tonal/proxyCacheLimits": typeof tonal_proxyCacheLimits;
  "tonal/proxyMemo": typeof tonal_proxyMemo;
  "tonal/proxyProjected": typeof tonal_proxyProjected;
  "tonal/refresh": typeof tonal_refresh;
  "tonal/refreshPublic": typeof tonal_refreshPublic;
  "tonal/resync": typeof tonal_resync;
  "tonal/scheduling": typeof tonal_scheduling;
  "tonal/schedulingReceipts": typeof tonal_schedulingReceipts;
  "tonal/strengthHistoryProjection": typeof tonal_strengthHistoryProjection;
  "tonal/syncQueries": typeof tonal_syncQueries;
  "tonal/tokenQueries": typeof tonal_tokenQueries;
  "tonal/tokenRefresh": typeof tonal_tokenRefresh;
  "tonal/tokenRetry": typeof tonal_tokenRetry;
  "tonal/transforms": typeof tonal_transforms;
  "tonal/types": typeof tonal_types;
  "tonal/validation": typeof tonal_validation;
  "tonal/workoutCatalogSync": typeof tonal_workoutCatalogSync;
  "tonal/workoutDetailProjection": typeof tonal_workoutDetailProjection;
  "tonal/workoutHistoryProxy": typeof tonal_workoutHistoryProxy;
  "tonal/workoutMeta": typeof tonal_workoutMeta;
  "trainingState/read": typeof trainingState_read;
  "trainingState/recovery": typeof trainingState_recovery;
  "trainingState/types": typeof trainingState_types;
  userActivity: typeof userActivity;
  userData: typeof userData;
  userMemoryFacts: typeof userMemoryFacts;
  userProfileActivity: typeof userProfileActivity;
  userProfiles: typeof userProfiles;
  users: typeof users;
  validators: typeof validators;
  weekPlanActions: typeof weekPlanActions;
  weekPlanApproval: typeof weekPlanApproval;
  weekPlanCompletion: typeof weekPlanCompletion;
  weekPlanDeletion: typeof weekPlanDeletion;
  weekPlanDeletionShared: typeof weekPlanDeletionShared;
  weekPlanDeletionSnapshot: typeof weekPlanDeletionSnapshot;
  weekPlanDeletionState: typeof weekPlanDeletionState;
  weekPlanEnriched: typeof weekPlanEnriched;
  weekPlanHelpers: typeof weekPlanHelpers;
  weekPlanInternals: typeof weekPlanInternals;
  weekPlans: typeof weekPlans;
  workflows: typeof workflows;
  workoutDeletionGuard: typeof workoutDeletionGuard;
  workoutDetail: typeof workoutDetail;
  workoutFeedback: typeof workoutFeedback;
  workoutPerformanceProjectionFreshness: typeof workoutPerformanceProjectionFreshness;
  workoutPlans: typeof workoutPlans;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  agent: import("@convex-dev/agent/_generated/component.js").ComponentApi<"agent">;
  perfByMovement: import("@convex-dev/aggregate/_generated/component.js").ComponentApi<"perfByMovement">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  rateLimiter: import("@convex-dev/rate-limiter/_generated/component.js").ComponentApi<"rateLimiter">;
  workflow: import("@convex-dev/workflow/_generated/component.js").ComponentApi<"workflow">;
};
